name: Builder
description:
  "Build website. Julia 1.9 and Python 3.10 are already installed on
  GitHub-hosted runners. Reference:
  https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md"
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install
      shell: bash

    - name: Activate and Instantiate
      run: |
        using Pkg
        Pkg.activate(".")
        Pkg.instantiate()
      shell: julia --color=yes {0}

    - name: Build
      run: bun prod
      shell: bash
