name: Builder
description:
  "Build website. Julia 1.6 and Python 3.8 are already installed on
  GitHub-hosted runners. Reference:
  https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md"
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: yarn install --prod --pure-lockfile
      shell: bash

    - name: Activate and Instantiate
      run: |
        using Pkg
        Pkg.activate(".")
        Pkg.instantiate()
      shell: julia --color=yes {0}

    - name: Build
      run: yarn prod
      shell: bash
