filters:
  comments: true
  allowlist:
    allow:
      - "/\\+\\+\\+[\\s\\S]*?\\+\\+\\+/m"
      - "/\\$\\$[\\s\\S]*?\\$\\$/m"
      - "/\\$.+?\\$/"
      - "/気が[しす]/"
      - "\\"
rules:
  prh:
    checkEmphasis: true
    checkHeader: true
    rulePaths:
      - "./.prh.yml"
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      lintStyledNode: true
    ja-space-around-code:
      before: true
      after: true
  preset-ja-technical-writing:
    ja-no-weak-phrase: false
    no-exclamation-question-mark: false
    ja-no-mixed-period:
      allowEmojiAtEnd: true
    sentence-length:
      max: 150
      exclusionPatterns:
        - "/（.*?）。$/"
    ja-no-redundant-expression:
      dictOptions:
        dict5:
          allows:
            - "/^通信を行[ぁ-ん]/"
            - "/^[ァ-ヶ]+を.?行[ぁ-ん]/"
            - "/^[a-zA-Z]+を.?行[ぁ-ん]/"
    max-kanji-continuous-len:
      max: 6
      allow:
        - "主小行列固有値"
        - "平均単位取得率"
        - "宇宙産業従事者"
