# /// script
# requires-python = ">=3.12"
# dependencies = ["fonttools[woff]"]
# ///
"""Subset Firge35Nerd Console to the characters the site uses.

Run: uv run site/theme/fonts/generate.py
"""

import io
import urllib.request
import zipfile
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

RELEASE = "https://github.com/yuru7/Firge/releases/download/v0.3.0/FirgeNerd_v0.3.0.zip"
WEIGHTS = {"Regular": 400, "Bold": 700}
# Latin, symbols, box drawing, Powerline.
BASE_RANGES = "0020-007E,00A0-00FF,0100-017F,2000-206F,20A0-20CF,2190-21FF,2200-22FF,2500-257F,25A0-25FF,E0A0-E0B3"
# 618/1024 (Firge35 "a") / 1233/2048 (Menlo "a").
FALLBACK_SIZE_ADJUST = "100.24%"

HERE = Path(__file__).parent
ROOT = HERE.parents[2]
TEXT_SOURCES = ["site/posts/**/*.md", "site/embeds.json", "packages/ssg/src/*.ts"]


def site_text() -> str:
    return "".join(p.read_text() for g in TEXT_SOURCES for p in ROOT.glob(g))


def subset_font(ttf: bytes, codepoints: set[int]) -> TTFont:
    font = TTFont(io.BytesIO(ttf))
    subsetter = subset.Subsetter(subset.Options(flavor="woff2"))
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    return font


def main() -> None:
    with urllib.request.urlopen(RELEASE) as r:
        zipped = zipfile.ZipFile(io.BytesIO(r.read()))
    codepoints = set(subset.parse_unicodes(BASE_RANGES)) | {ord(c) for c in site_text() if not c.isspace()}
    faces = []
    for weight_name, weight in WEIGHTS.items():
        font = subset_font(zipped.read(f"FirgeNerd_v0.3.0/Firge35NerdConsole-{weight_name}.ttf"), codepoints)
        name = f"Firge35NerdConsole-{weight_name}.woff2"
        font.save(HERE / name)
        faces.append(
            "@font-face {\n"
            '  font-family: "Firge35Nerd Console";\n'
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            f'  src: url("../fonts/{name}") format("woff2");\n'
            "  font-display: swap;\n"
            "}\n"
        )
    (HERE / "Firge35NerdConsole.chars.txt").write_text("".join(map(chr, sorted(codepoints))) + "\n")
    fallback = (
        "@font-face {\n"
        '  font-family: "Firge35Nerd Console Fallback";\n'
        '  src: local("Menlo"), local("Consolas"), local("Monaco");\n'
        f"  size-adjust: {FALLBACK_SIZE_ADJUST};\n"
        "}\n"
    )
    (HERE.parent / "css" / "font.css").write_text(
        "/* Generated by fonts/generate.py; do not edit. */\n" + "\n".join(faces) + "\n" + fallback
    )


if __name__ == "__main__":
    main()
