name: Staging

on:
  pull_request:
    branches:
      - master

  pull_request_target:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request_target' }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build
        uses: ./.github/actions/builder

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: staging
          folder: __site

  publish:
    needs: build-and-deploy
    environment:
      name: cloudflare-pages
      url: ${{ steps.cf-pages.outputs.url }}
    runs-on: ubuntu-22.04
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request_target' }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Publish to Cloudflare Pages
        id: cf-pages
        env:
          deploy_hook: ${{ secrets.DEPLOY_HOOK }}
        run: |
          result_id=$(curl -X POST "$deploy_hook" | awk -F'["-]' '/"id":/{print $4}')
          echo "::set-output name=url::https://${result_id}.stg.pages.dev"
