name: Staging

on:
  push:
    branches-ignore:
      - master
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/builder

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: staging
          FOLDER: __site
