name: Wiki Backlinks

on:
  gollum:
  workflow_dispatch:

env:
  WIKI_PATH: ${{ github.repository_id }}-wiki

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Clone Wiki
        run: |
          git clone "https://github.com/${{ github.repository }}.wiki.git" ${{ env.WIKI_PATH }}

      - name: Update Backlinks
        run: |
          .github/workflows/scripts/update-backlink.sh

      - name: Commit and Push
        working-directory: ${{ env.WIKI_PATH }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update backlinks"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git"
